name: Build Image

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, alpine-build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run build in Ubuntu 22.04 Docker container
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace ubuntu-22.04-build-env bash -c "
            chmod +x build.sh &&
            ./build.sh all &&
            TIMESTAMP=\$(date +%Y%m%d-%H%M%S) &&
            mv build/output/update.img build/output/update-\${TIMESTAMP}.img
          "

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: update-image
          path: build/output/update-*.img
