name: Build Image

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, alpine-build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean build directory (if exists)
        run: |
          if [ -d build ]; then
            sudo rm -rf build
          fi

      - name: Run build in Docker (Ubuntu 22.04)
        run: |
          docker run --rm --privileged \
            -v "$GITHUB_WORKSPACE:/workspace" \
            --mount type=bind,source=/dev,target=/dev \
            --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly \
            --mount type=bind,source=/etc/group,target=/etc/group,readonly \
            --mount type=bind,source=/etc/shadow,target=/etc/shadow,readonly \
            --mount type=bind,source=/etc/sudoers,target=/etc/sudoers,readonly \
            --u root \
            ubuntu-22.04-build-env bash -c "
              set -e
              cd /workspace
              chmod +x build.sh
              ./build.sh all
              TIMESTAMP=\$(date +%Y%m%d-%H%M%S)
              mv build/output/update.img build/output/update-\${TIMESTAMP}.img
            "

      - name: Upload update image artifact
        uses: actions/upload-artifact@v4
        with:
          name: update-image
          path: build/output/update-*.img
